import Header from '@/components/header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">        
      <body className='bg-gray-700 w-full h-screen absolute'>
        <Header />
        {children}
        </body>
    </html>
  )
}
